### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by daveneti** [corehunter/corehunter3-ui#1]

**Comment by daveneti** [comment]
This will fail until the correct corehunter gui-release branch is used.

**Comment by daveneti** [comment]
As expected fails because "Missing requirement: org.corehunter.ui.services 1.0.0.qualifier requires 'bundle uno.informatics.common.informatics-data-impl 1.0.5' but it could not be found" 

Need to test will clean build on local machine first. Depends on local modules in stalled in .m2

**Comment by daveneti** [comment]
Need to release version 3.1 of CoreHunter with required API changes, before continuing.

**Comment by daveneti** [comment]
@hdbeukel This travis build depends on a specific branch of corehunter3 (release/gui-develop to be precise). I assume that I need to merge this into develop and then release as CoreHunter 3.1 before proceeding. Or do you know of another approach where travis can get and install a specific branch of a dependent repository?

**Comment by hdbeukel** [comment]
I don't think that is possible. So yes you need to merge into develop, release a snapshot of 3.1 and use that as a dependency for the UI.

**Comment by daveneti** [comment]
I thought so. I have already merged in the branch. Let me do some final check then we can release.
