### ISSUE TITLE
Remove objective button not always active

### ISSUE THREAD

**Issue by hdbeukel** [corehunter/corehunter3-ui#5]
I loaded a dataset with genotypes and phenotypes, so the app correctly guessed that I wanted to optimize Modified Rogers' and Gower distance. But the remove objective button was greyed out so I could not remove one of the two objectives if I wanted to.

**Comment by guypfr** [comment]
You should be able to remove all but one objective. I will double check the logic. I think in this case it does not call a function to update the buttons.

**Comment by daveneti** [comment]
Found the problem, the objective viewer selection listener is added before the view is created and thus ignored. The buttons therefore never updated when the selection changes.
